name = "Blist"
license = "MIT"
licenselink = "https://github.com/apvarun/blist-hugo-theme/blob/master/LICENSE"
description = "Blist is a clean and fast blog theme for your Hugo site."
homepage = "https://github.com/apvarun/blist"
demosite = "https://blist.vercel.app"
tags = ["Hugo", "theme", "blog", "modern", "responsive"]
features = ["clean", "gallery", "minimal", "minimalist", "mobile", "personal", "responsive", "simple", "tailwind", "blog", "white"]
min_version = "0.82.1"

[author]
  name = "Varun A P"
  homepage = "https://apvarun.com"
